# Generated by Django 3.2.5 on 2021-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cc',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cp',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='empresa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='foto_cliente',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='puesto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto_producto',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
    ]
